version: 0.2

phases:
  pre_build:
    commands:
      - touch .env
      - echo $REACT_APP_REGION_AWS >> .env
      - echo $REACT_APP_CLIENT_ID_AWS >> .env
      - npm install
      - npm run lint
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build